- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "Contact"

- name: "Donate"
  url: "/donate/"
  title: "Donate"

- name: "RSS"
  url: "/feed.xml"
  title: "Subscribe to RSS Feed"
  
- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
